services:
  api:
    build: .
    env_file:
      - .env
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "${API_PORT:-8055}:8000"
    volumes:
      - ./externals.json:/app/externals.json:ro
      - ./files:/app/files:ro
    networks:
      - fastapi-net

networks:
  fastapi-net:
    driver: bridge
