services:
  api:
    build: .
    environment:
      DATABASE_URL: ${DATABASE_URL}
    ports:
      - "${API_PORT:-8055}:8000"
    networks:
      - fastapi-net

networks:
  fastapi-net:
    driver: bridge